{% set name = "radical.saga" %}
{% set version = "0.90.0" %}
{% set sha256 = "579e0d892ce381c05610c02af66fcaa753965f8dc9939b8ed8319597010be55b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed  .
  skip: True  # [py2k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - apache-libcloud
    - parse
    - radical.utils >=0.90.0
    
test:
  imports:
    - radical.saga
  
about:
  home: http://radical-cybertools.github.io/saga-python/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'RADICAL SAGA (Simple API for Grid Applications) defines a high-level interface to the most commonly used distributed computing functionality.'
  description: |
    RADICAL SAGA provides an access-layer and mechanisms for distributed infrastructure components like job 
    schedulers, file transfer and resource provisioning services. Given the heterogeneity of 
    distributed infrastructure, SAGA provides a much needed interoperability layer that lowers the 
    complexity and improves the simplicity of using distributed infrastructure whilst enhancing 
    the sustainability of distributed applications, services and tools. 
  dev_url: https://github.com/radical-cybertools/radical.saga

extra:
  recipe-maintainers:
    - andre-merzky
    - iparask
