{% set name = "radical.saga" %}
{% set version = "1.102.0" %}
{% set sha256 = "215b41f2ff421f1729c012bfa0d958bbd2f36ec912243f1c6a70fb4e62ae9134" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace(".", "_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - radical.utils >=1.100.0,<1.110
    - parse

test:
  imports:
    - radical.saga
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/radical-cybertools/radical.saga
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-SAGA defines a high-level interface for distributed computing infrastructures
  description: |
    RADICAL-SAGA (RS) is a Python package that implements the interface 
    specification of the Open Grid Forum (OGF) Simple API for Grid Applications 
    (SAGA) standard. RS works as a light-weight access layer for distributed 
    computing infrastructures, providing adaptors for different middleware 
    systems and services.
  doc_url: https://radicalsaga.readthedocs.io
  dev_url: https://github.com/radical-cybertools/radical.saga

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
