{% set name = "radical.saga" %}
{% set version = "1.90.0" %}
{% set sha256 = "55758339f58087477574ed598e5a34cb99d045a540a74ba9e11b34eead4af78d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace(".", "_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - apache-libcloud
    - parse
    - radical.utils >=1.60

test:
  imports:
    - radical.saga

about:
  home: https://github.com/radical-cybertools/radical.saga
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-SAGA defines a high-level interface for distributed computing infrastructures
  description: |
    RADICAL-SAGA (RS) is a Python package that implements the interface 
    specification of the Open Grid Forum (OGF) Simple API for Grid Applications 
    (SAGA) standard. RS works as a light-weight access layer for distributed 
    computing infrastructures, providing adaptors for different middleware 
    systems and services.
  doc_url: https://radicalsaga.readthedocs.io
  dev_url: https://github.com/radical-cybertools/radical.saga

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
