{% set name = "radical.saga" %}
{% set version = "1.60.0" %}
{% set sha256 = "1a69b0a9d06452ca8db9ebaa4a96b31ce28f61c267d73723e4e48a0fc4daa99f" %}

package:
  name: {{ name|lower }}
  name_pkg: {{ name|replace(".", "_") }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name_pkg }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - apache-libcloud
    - parse
    - radical.utils >=1.60

test:
  imports:
    - radical.saga

about:
  home: https://github.com/radical-cybertools/radical.saga
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-SAGA defines a high-level interface for distributed computing infrastructures
  description: |
    RADICAL-SAGA (RS) is a Python package that implements the interface 
    specification of the Open Grid Forum (OGF) Simple API for Grid Applications 
    (SAGA) standard. RS works as a light-weight access layer for distributed 
    computing infrastructures, providing adaptors for different middleware 
    systems and services.
  doc_url: https://radicalsaga.readthedocs.io
  dev_url: https://github.com/radical-cybertools/radical.saga

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
