{% set name = "radical.saga" %}
{% set version = "1.46.0" %}
{% set sha256 = "71288c592a32b080a797abea98de6dbb71da5a8032b4dc7021b0813584a02344" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - apache-libcloud
    - parse
    - radical.utils >=1.40

test:
  imports:
    - radical.saga

about:
  home: https://github.com/radical-cybertools/radical.saga
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-SAGA defines a high-level interface for distributed computing infrastructures
  description: |
    RADICAL-SAGA (RS) is a Python package that implements the interface 
    specification of the Open Grid Forum (OGF) Simple API for Grid Applications 
    (SAGA) standard. RS works as a light-weight access layer for distributed 
    computing infrastructures, providing adaptors for different middleware 
    systems and services.
  dev_url: https://github.com/radical-cybertools/radical.saga

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
