{% set name = "radical.saga" %}
{% set version = "1.81.0" %}
{% set sha256 = "e19550190dea5dd7173c12869f6c41351117304d2c87dba517addb78d1c297fa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace(".", "_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - apache-libcloud
    - parse
    - radical.utils >=1.60

test:
  requires:
    - python {{ python_min }}
  imports:
    - radical.saga

about:
  home: https://github.com/radical-cybertools/radical.saga
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-SAGA defines a high-level interface for distributed computing infrastructures
  description: |
    RADICAL-SAGA (RS) is a Python package that implements the interface 
    specification of the Open Grid Forum (OGF) Simple API for Grid Applications 
    (SAGA) standard. RS works as a light-weight access layer for distributed 
    computing infrastructures, providing adaptors for different middleware 
    systems and services.
  doc_url: https://radicalsaga.readthedocs.io
  dev_url: https://github.com/radical-cybertools/radical.saga

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
