travis:
  secure:
    BINSTAR_TOKEN: W9mkVadcpONJ1p4J9cKLZX5Lk3icv6BVcYDus5Fxzg8McNSmraC9W7HhVhR7DtRFOwPRZapIwwZLCjehOd2kTNDiALJLpqgXRNptN/wgZ9wbojnPtnX+DU+YE3DRCkGgW5lJWh/VrYuE+8ZLSCjfC+CCRp5esQYlwjiKjUkAPBMcQjqKnxAmkbMA4naY5+nP8te2tfZ3DVQoMK7OE9a0N+VUbr9B266Z9VSpkSiHPpw27wznrcPbr3KG8f/2KZ7IrjZggkgpGa/Qy801hycmGrY+uozuL/5bSprN2IXzl5fhTP9gkKSSgFD76KIe6bz5fRaIzuJWmcNsVfv64tnQa1zlMQVMV0cFcxJxjbFipHkr/LnQq4EoDeNJuF2do4KfT2cviTO573xHrG6scHqy0uct3wrPJmZKkLXmOUbb5G6Y5zcBdXWw1dc96T9jzkYSKQMnoEwN+25fDv6dbO5Ap6wVU751XM0UdwR4syw7R3PSygBNNJ/R/NTSniYCJ/NLZZEIQhnE03kDlGFjvhrA5zj5vDDEB3sdOQhrjy7luBPpZRvJ3/OhDRbhApeXxarMEw1jWPd8lNl3tRN4MBU/UqE4r0pvcglHx1gR4g61gARCG+78TAau+EGFIp3GFDJefCKfDep9Vhc+AspnBkknG8gcyUkTSBhmNbY123lbeiY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
