travis:
  secure:
    BINSTAR_TOKEN: dhpJXVU2ht71Zi4PC0coUPH+4IjQ9xk9AhXLdyxeRESZ1PlynHGkfznmF1URQ/h2acm75k677rduSW0APMuPmHH6tDvXyCRksDj3Tvr1nhpa3S5a4qmAaNvGyrJb482YB4VBRS/rZ6JuRdiQU5b3QUzQ28/OMGUG1F0qXfUpkp6aJG4crnccbjublZGKbo4AVBvKpBCKgwPQ/Ibhcprsg5DR/HkHZa+hc23fqJGJb68iqTc4om36NFPKlIkfYjHjOxjiDiQ6FZBjim6eN7rf4JNUA157otfwn5ZSDt36SL8LWY4unhRAo5XA8jJQDE2i0OjtDbS1U1SPbbDAnujtfDYqMgFvNmghagD5nGAHWGXDFJl7WiDccUIeyke16VE1yKzWlLXovxO0BdI+ppkq0tZnBHlo9Dtx55ypgt7B3peNOl3baZ/1SprzQ3KVRTvAHRoK1ZQsbOZjAOAlIs/QnQdhgCFUVfVQYms1umCo7Kv0Fc43s/Srop+wzxE8eJEQmMyDw/SMFWDzf3GasE4NJ1FqQ2XG7SOFyig3RHw0gMuSwp1zoU219izTVkAz3sxK4x9Oae0g0x7IM+KjLNa+zTadtF25LGW7SKAtBC3UsyfBy+DuhN71a+/DdjlnHGBC6YHZQ+LIV+YRaK9L8uMn29lrtogm53zrXKqOhMHb5K8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
