conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
noarch_platforms:
  - osx_64
  - linux_64
  - linux_ppc64le
provider:
  osx_64: azure
  linux_64: azure
  linux_ppc64le: default
github:
  branch_name: main
  tooling_branch_name: main
